# Generated by Django 3.2.1 on 2021-05-07 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Secteur')),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=512, verbose_name='Intitulé du projet')),
                ('responsable', models.CharField(max_length=64, verbose_name='Responsable')),
                ('convention', models.CharField(blank=True, max_length=64, null=True, verbose_name='N° Convention')),
                ('date_ouverture_plis', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('delais', models.IntegerField(default=1, help_text='Délais en mois')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_reception_provisoire', models.DateField(blank=True, null=True)),
                ('date_reception_definitive', models.DateField(blank=True, null=True)),
                ('titulaire', models.CharField(blank=True, max_length=128, null=True, verbose_name='Titulaire du marché')),
                ('marche', models.CharField(blank=True, max_length=64, null=True, verbose_name='N° Marché')),
                ('cout_global', models.FloatField(blank=True, null=True, verbose_name='Côut global')),
                ('etat_avancement', models.IntegerField(default=0, verbose_name="Etat d'avancement physique (%)")),
                ('etat', models.CharField(choices=[('PREPARATION', 'En phase de préparation'), ('LANCEMENT', 'En phase de lancement'), ('DEMARRAGE', 'En phase de démarrage'), ('ENCOURS', "Opérationnel en cours d'exécution"), ('ENRETARD', "En retard en cours d'exécution"), ('ENARRET', "En arrêt en cours d'exécution"), ('ARESILIER', 'A résilier'), ('TERMINE', 'Terminé')], default='PREPARATION', max_length=64, verbose_name='Etat projet')),
                ('reception', models.CharField(blank=True, choices=[('PROVISOIRE', 'Provisoire'), ('DEFINITIVE', 'Définitive')], max_length=64, null=True, verbose_name='Réception')),
                ('etat_lieu', models.TextField(blank=True, help_text="Etat des lieux à l'instant T", null=True, verbose_name='Etat des lieux')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('communes', models.ManyToManyField(to='projet.Commune')),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projet.secteur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
